import path from "node:path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";
import { resolveTauriCore } from "./src/shared/profiling/viteTauriCoreProxy";

const host = process.env.TAURI_DEV_HOST;

// Temporary profiling harness (never merges): route every Tauri core `invoke`
// through a proxy that wraps it. A resolver (not a bare alias) is required
// because Tauri's own submodules (`event`, `app`, `window`, `webview`, …) reach
// core via the relative import `./core.js`, which an alias cannot see; the hook
// redirects both the bare specifier and that relative form to the proxy, while
// the proxy's `@tauri-core-impl` import escapes to the real module.
const tauriCoreProxyId = path.resolve(
  __dirname,
  "./src/shared/profiling/tauriCoreProxy.ts",
);
const tauriRealCoreId = path.resolve(
  __dirname,
  "./node_modules/@tauri-apps/api/core.js",
);
const tauriCoreProfilingProxy = {
  name: "tauri-core-profiling-proxy",
  enforce: "pre" as const,
  resolveId(source: string, importer: string | undefined) {
    return resolveTauriCore(
      source,
      importer,
      tauriCoreProxyId,
      tauriRealCoreId,
    );
  },
};

// https://vite.dev/config/
export default defineConfig(async () => ({
  plugins: [
    tauriCoreProfilingProxy,
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: [
        "// biome-ignore-all lint: generated by TanStack Router",
      ],
    }),
    react(),
  ],
  resolve: {
    alias: {
      "@": "/src",
      "@features-manifest": path.resolve(__dirname, "../preview-features.json"),
      "@model-capabilities-manifest": path.resolve(
        __dirname,
        "../scripts/model-capabilities.json",
      ),
    },
  },

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent Vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: parseInt(process.env.VITE_PORT || "1420", 10),
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: parseInt(process.env.VITE_HMR_PORT || "1421", 10),
        }
      : undefined,
    watch: {
      // 3. tell Vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**"],
    },
  },
}));
